### ISSUE TITLE
Add todo button functionality

### ISSUE THREAD

**Issue by dothaionline** [dothaionline/College-Utils-iOS-App#5]
- [ ] When a todo is clicked, set it's `isComplete` to `!isComplete`.

- [ ] If it goes from incomplete to complete, change the color to light gray to show the user that that todo is done.

- [ ] If it goes from complete to incomplete, change it's color back to the course color.

- [ ] When the user clicks back, remove all the complete todos from the list.
